### ISSUE TITLE
drone.action.arm() is not working without the GPS connected?

### ISSUE THREAD

**Issue by MuhammadBilal1** [mavlink/MAVSDK-Python#228]
I were using the [PX4-Gazebo simulator (headless)](https://github.com/jonasvautherin/px4-gazebo-headless#px4-gazebo-simulator-headless) with the example [takeoff_and_land](https://github.com/mavlink/MAVSDK-Python/blob/master/examples/takeoff_and_land.py) and things were working fine.

After the simulator I tried to use the actual PixHawk 4 (PX4 firmware installed via QGroundControl) but the PixHawk I am using doesn't have the GPS Module connected. So when I try to run the [example](https://github.com/mavlink/MAVSDK-Python/blob/master/examples/takeoff_and_land.py) given above, I am stuck at the following:

```
Waiting for mavsdk_server to be ready...
Connected to mavsdk_server!
Waiting for drone to connect...
Drone discovered with UUID: 1
Waiting for drone to have a global position estimate...
```

Is there a way which can help me in feeding the coordinates to the methods?
Just like we have the [option in the simulator](https://github.com/jonasvautherin/px4-gazebo-headless#run-with-another-start-location) to send the coordinates.

**Comment by julianoes** [comment]
So why don't you connect a GPS? Do you just want to do simulation?

**Comment by MuhammadBilal1** [comment]
> So why don't you connect a GPS? Do you just want to do simulation?

1. Actually I don't have the GPS module.
2. Yes, its more likely the simulation but I want to do this with the PixHawk instead of the simulator.

**Comment by julianoes** [comment]
Ok, if you want to do simulation with a Pixhawk you would have to use HITL (hardware in the loop simulation).
Otherwise, without GPS, you can't really fly with MAVSDK because it mostly supports automated or offboard flight and that - in general - requires a position source such as flow or GPS.

**Comment by hi6otb** [comment]
Hi,
Can I fly with Realsense T265 in indoor?  By using MAVSDK-python.
I can see local_position_ned in QGC that is T265 data.
However I can't see "local/global pose" in ROS so "health.is_local_potision_ok" and "health.is_global_potision_ok" are "FALSE".

**Comment by julianoes** [comment]
@hi6otb the important thing is that PX4 must have a position estimate. You can do that by feeding visual position estimates from VIO sensors or flow modules. However, all of that is more of a PX4 thing to figure out. Have a look here https://dev.px4.io/master/en/ros/external_position_estimation.html.

Then, once you have a position estimate you should be able to use offboard control but not mission because mission (at least for PX4) requires GPS, so a "global" position estimate. At this point you will just have to ignore some of the health data because it doesn't apply.
